name: Manual Workflow

on:
  workflow_dispatch:   # 👈 Enables manual trigger
    inputs:
    environment:
        description: 'Select environment'
        required: true
        default: 'development'
      version:
        description: 'App version to deploy'
        required: false
        default: 'latest'

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"

      - name: Run a sample task
        run: echo "Running manual job for ${{ github.event.inputs.environment }} environment"
